name: Deploy para AWS

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar chave SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.AWS_SSH_KEY }}

      - name: Copiar arquivos para servidor
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.AWS_HOST }} << 'EOF'
            cd /home/ubuntu/todo-app
            git pull origin main
            docker compose down
            docker compose up -d --build
          EOF
